version: 2

models:
  - name: stg_local_bike__stocks
    columns:
      - name: stock_id
        tests:
          - unique
          - not_null
      - name: store_id
        tests:
          - relationships:
              to: ref('stg_local_bike__stores')
              field: store_id
      - name: product_id
        tests:
          - relationships:
              to: ref('stg_local_bike__products')
              field: product_id
  - name: stg_local_bike__products
    columns:
      - name: brand_id
        tests:
          - relationships:
              to: ref('stg_local_bike__brands')
              field: brand_id
      - name: category_id
        tests:
          - relationships:
              to: ref('stg_local_bike__category')
              field: category_id
  - name: stg_local_bike__order_items
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_local_bike__orders')
              field: order_id
      - name: product_id
        tests:
          - relationships:
              to: ref('stg_local_bike__products')
              field: product_id
  - name: stg_local_bike__staffs
    columns:
      - name: store_id
        tests:
          - relationships:
              to: ref('stg_local_bike__stores')
              field: store_id
  - name: stg_local_bike__orders
    columns:
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_local_bike__customers')
              field: customer_id
      - name: store_id
        tests:
          - relationships:
              to: ref('stg_local_bike__stores')
              field: store_id
      - name: staff_id
        tests:
          - relationships:
              to: ref('stg_local_bike__staffs')
              field: staff_id