version: 2

sources:
  - name: local_bike
    schema: local_bike
    tables:
      - name: brands
        description: "Table of bicycle brand"
        columns:
          - name: brand_id
            description: "Unique identifier of the brand"
            tests:
              - unique
              - not_null
          - name: brand_name
            description: "Name of the brand"
      - name: stocks
        description: "Table of product stocks"
        columns:
          - name: store_id
            description: "Identifier of the store"
            tests:
              - not_null
          - name: product_id
            description: "Identifier of the product"
            tests:
              - not_null
          - name: quantity
            description: "Remaining quantity in the store"
      - name: products
        description: "Table of products"
        columns:
          - name: product_id
            description: "Unique identifier of the product"
            tests:
              - unique
              - not_null
          - name: product_name
            description: "Name of the product"
          - name: brand_id
            description: "Name of the brand"
          - name: category_id
            description: "Name of the category"
          - name: model_year
            description: "Year of creation of the product"
          - name: list_price
            description: "Price of the product"
      - name: categories
        description: "Table of categories"
        columns:
          - name: category_id
            description: "Unique identifier of the category"
            tests:
              - unique
              - not_null
          - name: category_name
            description: "Name of the category"
      - name: staffs
        description: "Table of staffs"
        columns:
          - name: staff_id
            description: "Unique identifier of the staff"
            tests:
              - unique
              - not_null
          - name: first_name
            description: "Firt name of the staff"  
          - name: last_name
            description: "Last name of the staff"
          - name: email
            description: "Email of the staff"
          - name: phone
            description: "Phone number of the staff"
          - name: active
            description: "Is active flag 1 for Yes and 0 for No"
          - name: store_id
            description: "Identifier of the store"
          - name: manager_id
            description: "Identifier of the manager"
      - name: stores
        description: "Table of stores"
        columns:
          - name: store_id
            description: "Unique identifier of the store"
            tests:
              - unique
              - not_null
          - name: store_name
            description: "Name of the store"
          - name: phone
            description: "Phone number of the store"
          - name: email
            description: "Email of the store"
          - name: street
            description: "Street adress of the store"
          - name: city
            description: "City adress of the store"
          - name: state
            description: "State adress of the store"
          - name: zip_code
            description: "Zip code adress of the store"
      - name: order_items
        description: "Table of order items"
        columns:
          - name: order_id
            description: "Identifier of the order"
            tests:
              - not_null
          - name: item_id
            description: "Identifier of the item"
            tests:
              - not_null
          - name: product_id
            description: "Identifier of the product"
          - name: quantity
            description: "Quantity buy"
          - name: list_price
            description: "Price of the product"
          - name: discount
            description: "Discount applied"
      - name: orders
        description: "Table of orders"
        columns:
          - name: order_id
            description: "Unique identifier of the order"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Identifier of the customer"
          - name: order_status
            description: "Is validate flag 1 for Yes and 0 for No"
          - name: order_date
            description: "Date of the order"
          - name: required_date
            description: "Required date requested by the customer"
          - name: shipped_date
            description: "Shipping date"
          - name: store_id
            description: "Identifier of the store"
          - name: staff_id
            description: "Identifier of the staff who made the sale"
      - name: customers
        description: "Table of customers"
        columns:
          - name: customer_id
            description: "Unique identifier of the customer"
            tests:
              - unique
              - not_null
          - name: first_name
            description: "First name of the customer"
          - name: last_name
            description: "Last name of the customer"
          - name: phone
            description: "Phone of the customer"
          - name: email
            description: "Email of the customer"
          - name: street
            description: "Street adress of the customer"
          - name: city
            description: "City adress of the customer"
          - name: state
            description: "State adress of the customer"
          - name: zip_code
            description: "Zip code adress of the customer"          





